// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include "main.hpp"

// ─────────────────────────────────────────────────────────────────────────────
// [T1]  reference mazes from the assignment
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T1a: maze1 contains exactly 4 crosses", "[T1]")
{
    int maze[10][10] = {{0, 0, 0, 0, 1, 0, 0, 0, 0, 0},
                        {0, 0, 0, 1, 1, 1, 0, 0, 0, 0},
                        {0, 0, 0, 0, 1, 0, 0, 0, 0, 0},
                        {0, 1, 0, 0, 1, 0, 0, 0, 0, 0},
                        {1, 1, 1, 1, 1, 1, 0, 0, 0, 0},
                        {0, 1, 0, 0, 1, 1, 1, 0, 0, 0},
                        {0, 1, 0, 0, 1, 1, 1, 0, 0, 0},
                        {0, 1, 0, 0, 1, 0, 1, 1, 0, 0},
                        {0, 1, 0, 0, 1, 1, 1, 0, 0, 0},
                        {0, 1, 0, 0, 1, 1, 1, 0, 0, 0}};
    REQUIRE(findcross(maze) == 4);
}

TEST_CASE("T1b: maze2 contains exactly 2 crosses", "[T1]")
{
    int maze[10][10] = {{0, 0, 0, 0, 1, 0, 0, 0, 0, 0},
                        {0, 0, 0, 1, 0, 1, 0, 0, 0, 0},
                        {0, 0, 0, 0, 1, 1, 0, 0, 0, 0},
                        {0, 1, 0, 0, 1, 1, 1, 0, 0, 0},
                        {1, 0, 1, 1, 0, 1, 1, 0, 0, 0},
                        {0, 1, 0, 0, 1, 1, 1, 0, 0, 0},
                        {0, 1, 0, 0, 1, 1, 1, 0, 0, 0},
                        {0, 1, 0, 0, 1, 0, 1, 1, 0, 0},
                        {0, 1, 0, 0, 1, 1, 1, 0, 0, 0},
                        {0, 1, 0, 0, 1, 1, 1, 0, 0, 0}};
    REQUIRE(findcross(maze) == 2);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T2]  no-cross cases
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T2a: all-zero grid contains 0 crosses", "[T2]")
{
    int M[10][10] = {0};
    REQUIRE(findcross(M) == 0);
}

TEST_CASE("T2b: scattered isolated 1s contain 0 crosses", "[T2]")
{
    int M[10][10] = {0};
    M[2][2] = 1;
    M[5][5] = 1;
    M[7][3] = 1;
    REQUIRE(findcross(M) == 0);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T3]  single isolated cross (away from borders)
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T3a: one cross centered at (5,5)", "[T3]")
{
    int M[10][10] = {0};
    M[4][5] = 1;
    M[6][5] = 1;
    M[5][4] = 1;
    M[5][6] = 1;
    M[5][5] = 1;
    REQUIRE(findcross(M) == 1);
}

TEST_CASE("T3b: cross missing one arm — count is 0", "[T3]")
{
    int M[10][10] = {0};
    M[4][5] = 1;
    // M[6][5] missing
    M[5][4] = 1;
    M[5][6] = 1;
    M[5][5] = 1;
    REQUIRE(findcross(M) == 0);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T4]  border edge cases — a cross cannot be centered on row 0/9 or col 0/9
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T4a: cross-shape touching row 0 is not counted (no up neighbor)", "[T4]")
{
    int M[10][10] = {0};
    M[0][5] = 1;
    M[1][4] = 1;
    M[1][5] = 1;
    M[1][6] = 1;
    // would be a cross centered at (0,5) but row 0 has no up neighbor
    REQUIRE(findcross(M) == 0);
}

TEST_CASE("T4b: two non-overlapping crosses are both counted", "[T4]")
{
    int M[10][10] = {0};
    // first cross at (2,2)
    M[1][2] = 1; M[3][2] = 1; M[2][1] = 1; M[2][3] = 1; M[2][2] = 1;
    // second cross at (7,7)
    M[6][7] = 1; M[8][7] = 1; M[7][6] = 1; M[7][8] = 1; M[7][7] = 1;
    REQUIRE(findcross(M) == 2);
}
